import "flowbite";
import "./globals.css";
import Head from "next/head";

// import Navbar from './(platform)/component/Navbar';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="viewport-fit=cover" />
      </Head>

      <body>
        {/* <Navbar /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
