
import Head from "next/head";
import Navbar from './component/Navbar';
import Footer from './component/Fotter';
import 'remixicon/fonts/remixicon.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta name="viewport" content="viewport-fit=cover" />
        {/* Add other meta tags or title here */}
      </Head>
      <header>
        <Navbar />
      </header>
      <main>{children}</main>
      <Footer />
    </>
  );
}